### PR TITLE
Expose Magic Flags

### PR DESCRIPTION
**Pull request by boekkooi-lengoo**
Hello,

First of thank you very much for maintaining WASMagic and having a look at this PR.

The goal of this PR is to expose the [libmagic](https://man7.org/linux/man-pages/man3/libmagic.3.html) flags to the user. This will allow users of WASMagic to get more information about a file should they require it. This will for example allow a user to add the correct extension when a file is uploaded (using WASMagicFlags.EXTENSION).

I would really appreciate a review (and possibly a merge) of this PR :smile:

### CODE REVIEW

**Comment by moshen** [comment]
Thanks I'll take a look at this

**Comment by moshen** [comment]
This is a great addition, and something that has been on my personal TODO list. When I saw this it occurred to me that I should get my own changes out there (in #31) as those changes introduce several instantiation options.

I might merge my changes and then rebase yours on top of it, to change the addition of the instantiation param:
https://github.com/moshen/wasmagic/pull/30/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R66-R69

to be inside the options object created here:
https://github.com/moshen/wasmagic/pull/31/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R5-R22

Please let me know if you have any thoughts on this plan.

On another note, how did you find the developer experience making changes to this library?

**Comment by boekkooi-lengoo** [comment]
Hey @moshen 

Thanks a lot for merging the change and improving on what is there already via https://github.com/moshen/wasmagic/pull/31.
I like the new options object :smile: 

In regards to the developer experience it was easy to set up the project and apply the changes. 
Only thing which took me a bit was to understand the linkage between `types` and `src` but I'm also not sure how to improve :smile: 

Thanks again and have a great day!
Cheers,
Warnar

**Comment by moshen** [comment]
Thank you for the patch!

Ah yeah, with the code generation for the `libmagic-wrapper` Typescript would get a little unhappy. It's gone through a couple of iterations.

If you're curious I thought I'd start rolling in some other changes from my TODO list into a 1.0.0 release in #35

**Pull request closed without merging**
